---
openapi: 3.0.0
info:
  title: admission-prediction-api
  description: The API for the Admission Prediction project
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/yiqunz/HW4/1.0.0
  description: SwaggerHub API Auto Mocking
- url: http://localhost/
  description: Admission Prediction Api
paths:
  /predict:
    get:
      tags:
      - Predict
      description: returns predicted value
      operationId: getPredict
      parameters:
      - name: absence
        in: query
        description: number of times students absent to class
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: failures
        in: query
        description: number of past class failures to predict
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      - name: studytime
        in: query
        description: number of times students learn
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Prediction'
              example:
                G3_prediction: 10
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Prediction:
      type: object
      properties:
        G3_prediction:
          type: integer
          format: int32
    Error:
      type: object
      properties:
        message:
          type: string
        description:
          type: string
